language: node_js

branches:
  only:
  - master

install:
- npm install

before_script:
- git config --global user.name 'Victor Miguez'
- git config --global user.email 'victorcineis@gmail.com'

script:
- webpack -p --config ./webpack.config.js

after_success:
- mkdir deploy
- cp -r dist deploy
- cp index.html deploy
- cd deploy
- git init
- git remote add origin $DEPLOY_REPO
- git add -A .
- git commit -m $TRAVIS_BUILD_NUMBER
- git push -f -u -q origin master:gh-pages
